version: "3"
services:
  wallet-tracker:
    image: ghcr.io/localblock/wallet-tracker
    environment:
      - DATABASE_URL=YOUR_DATABASE_URL # postgresql://wallet-tracker:YOUR_DATABASE_PASSWWORD@localhost:5432/wallet-tracker?schema=public
      - SESSION_PASSWORD=YOUR_SESSION_PASSWORD # Iron Session - Private key used to encrypt the cookie. It has to be at least 32 characters long
      - ALCHEMY_APIKEY=YOUR_APIKEY # From Alchemy dashboard
      - ALCHEMY_AUTHTOKEN=YOUR_AUTHTOKEN # From Alchemy dashboard
    restart: always
    ports:
      - 3000:3000

  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=YOUR_DATABASE_PASSWWORD # Same password than wallet-tracker container
      - POSTGRES_USER=wallet-tracker # Create a database with same username
    volumes:
      - pgdata:/var/lib/postgresql/data